### ISSUE TITLE
Export Hero Ability Icons

### ISSUE THREAD

**Issue by Setup007** [xyx0826/QuickOverTool-WPF#1]
First of all: What an amazing tool you provided! Thank you very much!

Now to my question: Is there any way as of now to extract the icons of the heroes abilities as shown here: https://res.cloudinary.com/lmn/image/upload/e_sharpen:150,f_auto,fl_lossy,q_80/v1/gameskinnyc/l/u/c/lucio-abilities-23e01.png ?
Those should be the same that are used for the interface when playing a hero (bottom-right corner)

Kind regards
Setup

**Comment by xyx0826** [comment]
Hi,

I tried to do so but I am afraid that DataTool cannot extract "pure UI" assets at this moment. Since I am not the author of DataTool, I am also sending this issue to zingballyhoo to see if they want to add something :)

**Comment by xyx0826** [comment]
Hi Setup,

Zing is going to add this in the future. 

"Those icons should be easy for me to get, they are defined in the ability STU file. I'm not going to add that just yet, but I will work on it as soon as I can."

**Comment by Setup007** [comment]
That would be amazing! Thank you very much! :D

**Comment by ZingBallyhoo** [comment]
@Setup007 Just a quick update...

Extracting ability icons is now available in DataTool as `extract-abilities`. In the GUI it is called `Extract Abilities`

https://ci.appveyor.com/project/xyx0826/quickovertool-wpf/build/artifacts

**Comment by Setup007** [comment]
Holy shit that was fast! Thank you very much!
Can you explain to me how to get the new DataTool.exe?

**Comment by ZingBallyhoo** [comment]
@Setup007 The latest DataTool is always here: https://facepunch.com/showthread.php?t=1578997 (I keep the first post updated)

https://ci.appveyor.com/api/buildjobs/a68oiwqtsw6j1h8l/artifacts/dist%2Ftoolchain-release.zip

**Comment by Setup007** [comment]
Thank you very much!
