### ISSUE TITLE
请问哪里能下载到这个工具？

### ISSUE THREAD

**Issue by HuanMeng0** [xyx0826/QuickOverTool-WPF#2]
NGA上的版本已经不适用现在的游戏。

**Comment by xyx0826** [comment]
这个工具现在发布在 https://forum.facepunch.com/f/fbx/qxgy/Overwatch-Model-Thread-v2/ （英文），翻到后面有最新版本。此帖也是 DataTool 作者的更新帖以及守望先锋资源创作的讨论。
另外也可以从 https://ci.appveyor.com/project/xyx0826/quickovertool-wpf/branch/datatool 直接下载。点击 上方"Latest Build" >> 右侧"Artifacts">> "output\QuickDataTool.exe" 就可以下载最新版本。
新的汉化版本会在将来推出。
